[book]
title = "Rust로 이해하는 블록체인과 스마트 컨트랙트"
authors = []
language = "ko"
src = "src"

[build]
build-dir = "book"

[rust]
edition = "2024"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
additional-css = ["theme/custom.css"]
