[book]
title = "Rust + Blockchain 완전 정복"
authors = []
language = "ko"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
additional-css = ["theme/custom.css"]
