data-path = "/var/lib/besu"
genesis-file = "/config/genesis.json"
network-id = 1337

p2p-port = 30303
nat-method = "DOCKER"

rpc-http-enabled = true
rpc-http-host = "0.0.0.0"
rpc-http-port = 8545
rpc-http-api = ["ETH", "NET", "WEB3", "QBFT"]
host-allowlist = ["*"]
rpc-http-cors-origins = ["all"]

min-gas-price = 0
